### ISSUE TITLE
Decide on personalization DOM API structure

### ISSUE THREAD

**Issue by doublejosh** [tableau-mkt/groucho#32]
- [Draft of future docs](https://github.com/tableau-mkt/groucho/wiki/Full-Docs)
- PR: https://github.com/tableau-mkt/groucho/pull/31

### Questions
1. Desire for "pane" groups to help with page load behavior?
1. Semantic-ness and name-spacing?

### Structure Examples

**Highly name-spaced, grouped**
```html
<section data-groucho-pane="user.genre">
  <span data-groucho-filter="pop">Gaga</span>
  <span data-groucho-filter="rock">Zeppelin</span>
</section>
```

**Grouped property mapping, semantic items**
```html
<section data-groucho-pane="user.genre" data-groucho-attribute="genre">
  <span data-genre="pop">Gaga</span>
  <span data-genre="rock">Zeppelin</span>
</section>
```

**Embedded property, namespaced**
```html
<section>
  <span data-groucho-genre="pop">Gaga</span>
  <span data-groucho-genre="rock">Zeppelin</span>
</section>
```
```javascript
groucho.config.personalize = [{
  userProperty: 'user.genre',
  dataAttribute: 'genre',
}];
```

**Totally Semantic, no grouping**
```html
<section>
  <span data-genre="pop">Gaga</span>
  <span data-genre="rock">Zeppelin</span>
</section>
```
```javascript
groucho.config.personalize = [{
  userProperty: 'user.genre',
  dataAttribute: 'genre',
}];
```

**Comment by iamEAP** [comment]
My two cents: Groucho has great, widely applicable utility and, with it, some responsibility. I'd lean toward very namespace-heavy if you go this direction.

I think if you want to do a more semantic approach, you should integrate with an existing microdata format. To me, 'data-*' is explicitly meant more as a one-off dumping ground for application data with no inherent cross-application meaning.

**Comment by doublejosh** [comment]
While trying to integrate with a meta-data standard would be lovely, I think often such DOM adjustment items would not correspond to semantic object represented by microdata formats.

Perhaps then the two remaining questions...
1. Should there be grouping panes?
1. Should configuration be at the pane level or global?

**Comment by doublejosh** [comment]
Via @iamEAP....

We should fire events from groucho that we can hang logging on.  Currently our other personalization tools drawing from data-sources have logging included, but that's proprietary and company specific.

**Comment by doublejosh** [comment]
I haven't been able to find any micro-formats intending to mark arbitrary page content sections/elements with topical relevance.  But at the very least, here are some patterns to draw from.

http://microformats.org/wiki/h-item
http://microformats.org/wiki/value-class-pattern
http://microformats.org/wiki/include-pattern
http://microformats.org/wiki/user-interface

**Comment by doublejosh** [comment]
**1)** Using a global adjustments manifest is a must have so it can be configured site wide to map from DOM to localstorage and params, allowing mappers/helpers.
```javascript
groucho.config.personalize = [{
  userProperty: 'user.genre',
  urlParameter: 'utm_genre',
  helperCallback: 'myNamespace.myHelper',
  // One of the following...
  dataClass: 'genre',
  dataAttribute: 'genre'
}];
```
**2)** If left empty (`groucho.config.personalize`) it should attempt to adjust all DOM markers using a matching param or user property.
```javascript
groucho.config.personalize = true; // default
```
```html
<span data-groucho-company-size="enterprise">Tag line</span>
<span data-groucho-industry="banking">Super relevant quote</span>
```

**3)** Wrapper panes should not be required, as plenty of items are one-off, not a list (as seen above).  They still might be helpful/necessary... but potentially optional/suggested for UX improvements.

**4)** DOM choices are still up in the air, and classes should be considered.  Some new thoughts...
```html
<span class="groucho-company-size_enterprise">Tag line</span>
<span class="groucho-industry groucho-industry-banking">Super relevant quote</span>
```

```html
<span data-groucho="company-size" class="copmany-size-enterprise">Tag line</span>
<span data-groucho="industry" class="banking">Super relevant quote</span>
```

**Comment by angrytoast** [comment]
Couple of thoughts:
- `data-groucho` is generic, `data-groucho-adjust` or something telling what the value means would be clearer
- There isn't really much momentum around microdata / semantic web related agreements. They are also primarily around machine identification and linking of things. You might browse over https://html.spec.whatwg.org/multipage/microdata.html or https://en.wikipedia.org/wiki/RDFa#HTML5_.2B_RDFa_1.1 if you want to more strictly align to markup embedded info, but I think the benefits aren't that clear
- Using a BEM-ish naming convention would be the way to go if you're going to use `class` as a data marker, or use another attribute all together, like `data-groucho-variant`

**Comment by doublejosh** [comment]
Seems like the markup consensus might be...
```html
<span data-groucho-adjust="org-size" data-groucho-variant="enterprise">Tag line</span>
```
AND...
```html
<span data-groucho-adjust="org-size">
  <span data-groucho-variant="enterprise">Tag line</span>
  <span data-groucho-variant="small">Tag line</span>
</span>
```

**Comment by doublejosh** [comment]
Though being more concise is achievable...

```javascript
groucho.config.personalize = [{
  userProperty: 'user.org-size',
  urlParameter: 'utm_orgsize',
  helperCallback: 'Tabia.personal.orgTermId',
  dataAttribute: 'org-size'
}];
```

```html
<span data-org-size="enterprise">Tag Line</span>
```

**Comment by doublejosh** [comment]
Could allow this as the default with no configs...
```
<span data-groucho.user.orgSize="enterprise">Tag Line</span>
```
