### ISSUE TITLE
Create hasUserSeen() for tracking comparison

### ISSUE THREAD

**Issue by doublejosh** [tableau-mkt/groucho#5]
Would be lovely to provide a way to ask has this user seen something. This will invariably we used for different types of things: taxonomy, nodes, urls, so it should accept a type param.

**Easy**
```
hasUserSeen('node', nid)
hasUserSeen('term', tid)
```
**Maybe?**
```
thing = { entity: { 'type': 'node', 'bundle': 'article' } };
hasUserSeen(thing, id);
```

**Comment by pvanoverbeek** [comment]
@doublejosh what is the status of this item? Are you still working on this or can it be closed?
